In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import ensemble
from sklearn.metrics import mean_absolute_error
import joblib

In [71]:
data =  pd.read_csv(r'C:\Users\Dilpat Rai\Desktop\Pandas\Melbourne_housing_FULL.csv')

In [45]:
data.head(n = 5)

,Suburb,Rooms,Type,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea
0,Abbotsford,2,h,NaN,2.5,2.0,1.0,1.0,126.0,NaN,NaN,Yarra City Council
1,Abbotsford,2,h,1480000.0,2.5,2.0,1.0,1.0,202.0,NaN,NaN,Yarra City Council
2,Abbotsford,2,h,1035000.0,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra City Council
3,Abbotsford,3,u,NaN,2.5,3.0,2.0,1.0,0.0,NaN,NaN,Yarra City Council
4,Abbotsford,3,h,1465000.0,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra City Council

In [46]:
data.dropna(axis=0, how='any', thresh=None, subset=None, inplace=True)

In [47]:
data.head(5)

,Suburb,Rooms,Type,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea
2,Abbotsford,2,h,1035000.0,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra City Council
4,Abbotsford,3,h,1465000.0,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra City Council
6,Abbotsford,4,h,1600000.0,2.5,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra City Council
11,Abbotsford,3,h,1876000.0,2.5,4.0,2.0,0.0,245.0,210.0,1910.0,Yarra City Council
14,Abbotsford,2,h,1636000.0,2.5,2.0,1.0,2.0,256.0,107.0,1890.0,Yarra City Council

In [48]:
features_df = pd.get_dummies(data, columns=['Suburb', 'CouncilArea', 'Type'])

In [49]:
features_df

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Suburb_Abbotsford,...,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Type_h,Type_t,Type_u
2,2,1035000.0,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,1,...,0,0,0,0,0,1,0,1,0,0
4,3,1465000.0,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,1,...,0,0,0,0,0,1,0,1,0,0
6,4,1600000.0,2.5,3.0,1.0,2.0,120.0,142.0,2014.0,1,...,0,0,0,0,0,1,0,1,0,0
11,3,1876000.0,2.5,4.0,2.0,0.0,245.0,210.0,1910.0,1,...,0,0,0,0,0,1,0,1,0,0
14,2,1636000.0,2.5,2.0,1.0,2.0,256.0,107.0,1890.0,1,...,0,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34847,3,500000.0,25.5,3.0,2.0,2.0,383.0,118.0,2016.0,0,...,0,0,0,1,0,0,0,1,0,0
34849,3,570000.0,25.5,3.0,2.0,2.0,404.0,158.0,2012.0,0,...,0,0,0,1,0,0,0,1,0,0
34853,2,888000.0,6.3,2.0,2.0,1.0,98.0,104.0,2018.0,0,...,0,0,0,0,0,0,0,1,0,0
34854,2,705000.0,6.3,2.0,1.0,2.0,220.0,120.0,2000.0,0,...,0,0,0,0,0,0,0,0,1,0
34856,2,1020000.0,6.3,2.0,1.0,0.0,250.0,103.0,1930.0,0,...,0,0,0,0,0,0,0,1,0,0

In [50]:
del features_df["Price"]

In [55]:
X = features_df.to_numpy()
y = data['Price'].to_numpy()

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

## We can change the max_depth for accuracy according to model fitting and we can also change the n_estimators according to results

In [63]:
model = ensemble.GradientBoostingRegressor(
n_estimators=150, #how many decision tree to build
learning_rate=0.1, #controls the rate at which additional decision trees influence the overall prediction.
max_depth=5, #(30) max number of layers(depth) 
min_samples_split=4, #min number of samples require to create new branch(binary) 
min_samples_leaf=6, #min no of samples appear in child node 
max_features=0.6, #total number of features presented to the model when etermining the best split
loss='huber' # model error rate
)

In [64]:
model.fit(X_train, y_train)

GradientBoostingRegressor(loss='huber', max_depth=5, max_features=0.6,
                          min_samples_leaf=6, min_samples_split=4,
                          n_estimators=150)

In [65]:
joblib.dump(model, 'house_trained_model.pkl')

['house_trained_model.pkl']

In [66]:
mse = mean_absolute_error(y_train, model.predict(X_train))
print ("Training Set Mean Absolute Error: %.2f" % mse)

Training Set Mean Absolute Error: 136034.70

In [67]:
mse = mean_absolute_error(y_test, model.predict(X_test))
print ("Test Set Mean Absolute Error: %.2f" % mse)

Test Set Mean Absolute Error: 165571.68